export const data = {
    projetosFront: [
        {id: 1, label: "Loja B7Story", link: "/projetos/b7story", linkProjeto: "https://b7store.vercel.app/", img: "/assets/projetos/b7store.png", github: "https://github.com/Marcio-Moraes/b7store", tech: ["Reactjs", "Nextjs", "typescript", "Tailwindcss", "zustand"], desc: "Loja de vestuário com temas de tecnologia."},
        {id: 2, label: "Portfolio Pessoal", link: "/projetos/portfolionext", linkProjeto: "https://marciomsilva.com.br", img: "/assets/projetos/portfolio-nextjs.png", github: "https://github.com/Marcio-Moraes/portfolio-nextjs", tech: ["Reactjs", "Nextjs", "Typescript", "tailwindcss", "Shadcn-UI"], desc: "Portfolio pessoal, com link de deploy e github."},
        {id: 3, label: "Sistema de Estacionamentos", link: "/projetos/sistema-despesasp", linkProjeto: "https://estapar-marcio.vercel.app/login", img: "/assets/projetos/estapar-estacionamentos-marcio-moraes.png", github: "https://github.com/Marcio-Moraes/estapar_marcio", tech: ["Reactjs", "Nextjs", "Typescript", "Tailwindcss", "Effect", "States"], desc: "Controle de estacionamentos. Com garagens e Mensalistas"},
        {id: 4, label: "NextCent - Landing Page", link: "/projetos/nextcent-landing", linkProjeto: "https://nextcent-six-rho.vercel.app/", img: "/assets/projetos/nexcent.png", github: "https://github.com/Marcio-Moraes/nextcent", tech: ["Reactjs", "Nextjs", "Typescript", "Tailwindcss", ], desc: "Landing page para a empresa NextCent."},
    ],
    icones: [
        {id: 1, img: "/assets/icons-svg/react.svg", nomeIcon: 'React'},
        {id: 2, img: "/assets/icons-svg/nextjs.svg", nomeIcon: 'Next.js'},
        {id: 3, img: "/assets/icons-svg/typescript.svg", nomeIcon: 'TypeScript'},
        {id: 4, img: "/assets/icons-svg/js.svg", nomeIcon: 'JavaScript'},
        {id: 5, img: "/assets/icons-svg/node-js.svg", nomeIcon: 'Node.js'},
        {id: 6, img: "/assets/icons-svg/vs-code.svg", nomeIcon: 'VS Code'},
        {id: 7, img: "/assets/icons-svg/cursor.svg", nomeIcon: 'Cursor'},
        {id: 8, img: "/assets/icons-svg/devin.svg", nomeIcon: 'Devin'},
        {id: 9, img: "/assets/icons-svg/antigravity.svg", nomeIcon: 'Antigravity'},
        {id: 10, img: "/assets/icons-svg/opencode.svg", nomeIcon: 'OpenCode'},
        {id: 11, img: "/assets/icons-svg/figma.svg", nomeIcon: 'Figma'},
        {id: 12, img: "/assets/icons-svg/php.svg", nomeIcon: 'PHP'},
        {id: 13, img: "/assets/icons-svg/wordpress.svg", nomeIcon: 'WordPress'},
        {id: 14, img: "/assets/icons-svg/npm.svg", nomeIcon: 'npm'},
        {id: 15, img: "/assets/icons-svg/tailwindcss.svg", nomeIcon: 'tailwindcss'},
    ],
    iconesSvg: [
        // Frameworks e Bibliotecas (prioridade)
        {id: 1, img: "/assets/icons-svg/react.svg", nomeIcon: 'React'},
        {id: 2, img: "/assets/icons-svg/nextjs.svg", nomeIcon: 'Next.js'},
        {id: 3, img: "/assets/icons-svg/vercel.svg", nomeIcon: 'Vercel'},
        {id: 4, img: "/assets/icons-svg/npm.svg", nomeIcon: 'npm'},
        // Linguagens de Programação
        {id: 5, img: "/assets/icons-svg/html-5.svg", nomeIcon: 'HTML5'},
        {id: 6, img: "/assets/icons-svg/css-3.svg", nomeIcon: 'CSS3'},
        {id: 7, img: "/assets/icons-svg/js.svg", nomeIcon: 'JavaScript'},
        {id: 8, img: "/assets/icons-svg/typescript.svg", nomeIcon: 'TypeScript'},
        {id: 9, img: "/assets/icons-svg/node-js.svg", nomeIcon: 'Node.js'},
        {id: 10, img: "/assets/icons-svg/php.svg", nomeIcon: 'PHP'},
        {id: 11, img: "/assets/icons-svg/wordpress.svg", nomeIcon: 'WordPress'},
        // IDEs e Editores
        {id: 12, img: "/assets/icons-svg/vs-code.svg", nomeIcon: 'VS Code'},
        {id: 13, img: "/assets/icons-svg/sublime-text.svg", nomeIcon: 'Sublime Text'},
        {id: 14, img: "/assets/icons-svg/atom.svg", nomeIcon: 'Atom'},
        {id: 15, img: "/assets/icons-svg/cmd.svg", nomeIcon: 'CMD'},
        {id: 16, img: "/assets/icons-svg/cursor.svg", nomeIcon: 'Cursor'},
        {id: 17, img: "/assets/icons-svg/devin.svg", nomeIcon: 'Devin'},
        {id: 19, img: "/assets/icons-svg/antigravity.svg", nomeIcon: 'Antigravity'},
        // Ferramentas de Desenvolvimento
        {id: 20, img: "/assets/icons-svg/git.svg", nomeIcon: 'Git'},
        {id: 21, img: "/assets/icons-svg/github.svg", nomeIcon: 'GitHub'},
        {id: 22, img: "/assets/icons-svg/githubcopilot.svg", nomeIcon: 'GitHub Copilot'},
        {id: 23, img: "/assets/icons-svg/docker.svg", nomeIcon: 'Docker'},
        // Bancos de Dados
        {id: 24, img: "/assets/icons-svg/mysql.svg", nomeIcon: 'MySQL'},
        {id: 25, img: "/assets/icons-svg/mariadb.svg", nomeIcon: 'MariaDB'},
        // Ferramentas de Design
        {id: 26, img: "/assets/icons-svg/figma.svg", nomeIcon: 'Figma'},
        {id: 27, img: "/assets/icons-svg/adobe-illustrator.svg", nomeIcon: 'Adobe Illustrator'},
        {id: 28, img: "/assets/icons-svg/adobe-photoshop.svg", nomeIcon: 'Adobe Photoshop'},
        {id: 29, img: "/assets/icons-svg/adobe-xd.svg", nomeIcon: 'Adobe XD'},
        // Navegadores
        {id: 30, img: "/assets/icons-svg/chrome.svg", nomeIcon: 'Chrome'},
        {id: 31, img: "/assets/icons-svg/firefox.svg", nomeIcon: 'Firefox'},
        // Outras Ferramentas
        {id: 32, img: "/assets/icons-svg/trello.svg", nomeIcon: 'Trello'},
        {id: 33, img: "/assets/icons-svg/slack.svg", nomeIcon: 'Slack'},
        {id: 34, img: "/assets/icons-svg/dropbox.svg", nomeIcon: 'Dropbox'},
        {id: 35, img: "/assets/icons-svg/stripe.svg", nomeIcon: 'Stripe'},
        {id: 36, img: "/assets/icons-svg/bitrix24.svg", nomeIcon: 'Bitrix24'},
        {id: 37, img: "/assets/icons-svg/gather.svg", nomeIcon: 'Gather'},
        {id: 38, img: "/assets/icons-svg/opencode.svg", nomeIcon: 'OpenCode'},
        {id: 39, img: "/assets/icons-svg/tailwindcss.svg", nomeIcon: 'tailwindcss'},
    ],
}